version: '3'

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 80:80
    depends_on:
      - web
  web:
    build: .
#    command: python manage.py runserver 0.0.0.0:8000
#    command: gunicorn optdemo_project.wsgi:application --bind 0.0.0.0:8000
    command: gunicorn optdemo_project.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
      - .:/usr/src/app/
    ports:
      - 8080:8080  # local
    #expose:
    #  - 8080      # GCP
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db

  test:
    build: .
    command: python manage.py test
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env.prod # 테스트도 동일한 환경 변수 사용
    depends_on:
      - db # 테스트 시 데이터베이스 연결이 필요하므로 의존성 추가

volumes:
  postgres_data:
  static_volume:
  media_volume:

