# Generated by Django 5.2.2 on 2025-08-01 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('run_id', models.CharField(db_index=True, max_length=50)),
                ('eq_name', models.CharField(db_index=True, max_length=255)),
                ('eq_group', models.CharField(blank=True, help_text='제약의 논리적 그룹 (예: one_game_per_slot)', max_length=100, null=True)),
                ('eq_type', models.CharField(blank=True, help_text='제약 유형 (예: Linear, Indicator)', max_length=50, null=True)),
                ('sign', models.CharField(help_text='<=, >=, ==', max_length=2)),
                ('rhs', models.FloatField(default=0.0, help_text='Right-Hand Side (우변) 값')),
                ('slot', models.IntegerField(blank=True, null=True)),
                ('home_team', models.CharField(blank=True, max_length=100, null=True)),
                ('away_team', models.CharField(blank=True, max_length=100, null=True)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'unique_together': {('run_id', 'eq_name')},
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('run_id', models.CharField(db_index=True, max_length=50)),
                ('var_name', models.CharField(db_index=True, max_length=255)),
                ('var_group', models.CharField(blank=True, help_text='변수의 논리적 그룹 (예: plays, is_at_loc)', max_length=100, null=True)),
                ('var_type', models.CharField(help_text='BINARY, INTEGER, CONTINUOUS', max_length=20)),
                ('lower_bound', models.FloatField(default=0.0)),
                ('upper_bound', models.FloatField(default=1.0)),
                ('result_value', models.FloatField(blank=True, help_text='최적화 후 변수의 값', null=True)),
                ('slot', models.IntegerField(blank=True, null=True)),
                ('home_team', models.CharField(blank=True, max_length=100, null=True)),
                ('away_team', models.CharField(blank=True, max_length=100, null=True)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'unique_together': {('run_id', 'var_name')},
            },
        ),
        migrations.CreateModel(
            name='MatrixEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, max_length=50)),
                ('coefficient', models.FloatField()),
                ('equation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.equation')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.variable')),
            ],
            options={
                'unique_together': {('variable', 'equation')},
            },
        ),
    ]
