"""
Django settings for optdemo_project project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# STATIC_URL = '/static/'
##MEDIA_URL 및 MEDIA_ROOT 설정 (파일 업로드 시 필요에 따라 사용)
# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'
# if not os.path.exists(MEDIA_ROOT):
#     os.makedirs(MEDIA_ROOT)

# 버킷 이름 변수화
GS_BUCKET_NAME ='optimization-demo-storages'
# 3. 정적 파일(Static Files) 설정
# 이제부터 정적 파일은 Cloud Storage를 통해 관리됩니다.
STATICFILES_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
# collectstatic 실행 시 파일이 저장될 버킷 내 경로 (URL과 일치시킴)
STATIC_ROOT = f"static/"
# 웹페이지에서 정적 파일을 불러올 URL 주소
STATIC_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/static/'
# 4. 미디어 파일(Media Files) 설정
# 사용자가 업로드하는 파일도 Cloud Storage를 통해 관리됩니다.
DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
# 업로드된 파일이 저장될 버킷 내 경로
MEDIA_ROOT = f"media/"
# 웹페이지에서 미디어 파일을 불러올 URL 주소
MEDIA_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/media/'
# 5. (중요) 접근 제어 설정
# 2단계에서 버킷 전체에 '균일(Uniform)' 권한을 부여했으므로,
# 개별 파일 업로드 시 ACL(접근 제어 목록)을 설정할 필요가 없습니다.
GS_DEFAULT_ACL = None
DEMO_DIR = f'{MEDIA_ROOT}/demo'
DEMO_DIR_MAP ={'matching_cf_tft_data': f'{DEMO_DIR}/match_cf_tft_data',
               'matching_transport_data':f'{DEMO_DIR}/matching_transport_data',
               'matching_resource_data':f'{DEMO_DIR}/matching_resource_data',
               'allocation_datacenter_data':f'{DEMO_DIR}/allocation_datacenter_data',
               'allocation_budjet_data':f'{DEMO_DIR}/allocation_budjet_data',
               'routing_vrp_data':f'{DEMO_DIR}/routing_vrp_data',
               'routing_cvrp_data':f'{DEMO_DIR}/routing_cvrp_data',
               'routing_pdp_data':f'{DEMO_DIR}/routing_pdp_data'}



dotenv_path = BASE_DIR / '.env'
load_dotenv(dotenv_path=dotenv_path)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY=os.environ.get('SECRET_KEY', 'django-insecure-5)=z06nprnb$ua_#)c**%n01&+*0%+d33lfqnl1l0n3qolcurx')
DEBUG=os.environ.get('DEBUG', 'False').upper()=='TRUE'
allowed_hosts_str=os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1')
#ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_str.split(',') if host.strip()]
ALLOWED_HOSTS = ['driven-current-462812-j1.an.r.appspot.com']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',          # core 앱 추가
    'matching_assignment_app',  # matching_assignment_app 추가
    'resource_allocation_app',  # 예시
    'routing_logistics_app',  # 예시
    'production_scheduling_app',  # 예시
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'optdemo_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'optdemo_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'mydatabase',
        'USER': 'myuser',
        'PASSWORD': 'supersecretpassword123', # 3단계에서 Secret Manager로 관리하는 것을 추천
        # Cloud SQL 연결을 위한 소켓 경로
        'HOST': '/cloudsql/driven-current-462812-j1:asia-northeast3:optimization-demo-db',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================================================================
# Logging Configuration
# ==============================================================================
LOGGING_CONFIG_MODULE_PATH = 'optdemo_project.logging_config'
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'debug_colored': {
            # '()'는 사용할 포맷터 클래스의 경로를 지정합니다.
            '()': f'{LOGGING_CONFIG_MODULE_PATH}.ColoredFormatter',
            'format': '[%(asctime)s] [%(levelname)s] %(name)s: %(message)s', # debug_format
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'info_colored': {
            '()': f'{LOGGING_CONFIG_MODULE_PATH}.ColoredFormatter',
            'format': '[%(asctime)s] [%(levelname)s] %(message)s', # info_format
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'solve_colored': {
            '()': f'{LOGGING_CONFIG_MODULE_PATH}.ColoredFormatter',
            'format': '[%(asctime)s] [%(levelname)s] %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'filters': {
        'debug_only': {
            # '()'는 사용할 필터 클래스의 경로를 지정합니다.
            '()': f'{LOGGING_CONFIG_MODULE_PATH}.LevelFilter',
            'level': 'DEBUG', # logging.DEBUG 값을 직접 쓰기보다 문자열로 지정
        },
        'solve_only': {
            '()': f'{LOGGING_CONFIG_MODULE_PATH}.LevelFilter',
            'level': 'SOLVE', # 문자열로 'SOLVE' 지정
        },
        # INFO 레벨만 처리하는 필터 (선택 사항)
        # 'info_only': {
        #     '()': f'{LOGGING_CONFIG_MODULE_PATH}.LevelFilter',
        #     'level': 'INFO',
        # },
    },
    'handlers': {
        'console_debug': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'debug_colored',
            'filters': ['debug_only'], # DEBUG 레벨 로그만 이 핸들러가 처리
        },
        'console_info_plus': { # INFO 레벨 이상
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'info_colored',
            # 이 핸들러는 DEBUG를 제외한 INFO, WARNING, ERROR, CRITICAL을 처리
            # 별도 필터 없으면 INFO 이상 모두 처리
        },
        'console_solve': {
            'level': 'SOLVE',
            'class': 'logging.StreamHandler',
            'formatter': 'solve_colored',
            'filters': ['solve_only'], # SOLVE 레벨 로그만 이 핸들러가 처리
        },
    },
    'root': {  # 루트 로거 설정: 모든 로거의 기본 설정
        'handlers': ['console_debug', 'console_info_plus', 'console_solve'],  # 사용할 핸들러 지정
        'level': 'DEBUG',  # 루트 로거의 레벨을 DEBUG로 설정해야 하위 핸들러들이 동작 가능
    },
    'loggers': {
        'django': { # Django 프레임워크 로그
            'handlers': ['console_info_plus'],
            'level': 'INFO', # INFO 레벨 이상만 기록
            'propagate': False,
        },
        'core': {
             'handlers': ['console_info_plus'],
             'level': 'INFO',
             'propagate': False,
        },
        'matching_assignment_app': { # 우리 앱 로거
            'handlers': ['console_debug', 'console_info_plus', 'console_solve'],
            'level': 'DEBUG', # 개발 시 DEBUG, 운영 시 INFO 로 변경 가능
            'propagate': False,
        },
        'resource_allocation_app': { # 우리 앱 로거
            'handlers': ['console_debug', 'console_info_plus', 'console_solve'],
            'level': 'SOLVE', # 개발 시 DEBUG, 운영 시 INFO 로 변경 가능
            'propagate': False,
        },
        'routing_logistics_app': { # 우리 앱 로거
            'handlers': ['console_debug', 'console_info_plus', 'console_solve'],
            'level': 'DEBUG', # 개발 시 DEBUG, 운영 시 INFO 로 변경 가능
            'propagate': False,
        },
        'production_scheduling_app': { # 우리 앱 로거
            'handlers': ['console_debug', 'console_info_plus', 'console_solve'],
            'level': 'INFO', # 개발 시 DEBUG, 운영 시 INFO 로 변경 가능
            'propagate': False,
        },
    },
}

